sudo: required
dist: trusty

script:
  # Install dotnet core
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install dotnet-dev-1.0.0-preview2-003121 --yes
  # Install ELM binaries
  - npm install -g elm
  # Print dotnet core info
  - dotnet --info
  # Build solution
  - dotnet restore
  - dotnet build ./Awesome.Trello -c Release

before_deploy:
  - rm Awesome.Trello/.gitignore
  - git add .
  - git commit -m "Compile ELM"

deploy:
  provider: azure_web_apps
  on: master
