sudo: required
dist: trusty

language: node_js
node_js:
  - node

env:
  global:
  - GH_USER: lijunle
  - GH_REPO: github.com/lijunle/awesome-trello.git

script:
  - npm install --production
  - node Awesome.Trello/elm-build.js

deploy:
  provider: script
  skip_cleanup: true
  script: node Awesome.Trello/elm-deploy.js
  on: master
